version: '3.3'
services:
  jekyll:
    build:
      context: .
    volumes:
      - '.:/srv/jekyll:Z'
      - './vendor/bundle:/usr/local/bundle:Z'
    ports:
      - '[::1]:4000:4000'
    image: jekyll/jekyll:4.2.2
